#╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬#
#╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬#
#╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬#

#                                                            ╔══════════════════════════╗
#                                                            ║    EBP INSTALLER 2022    ║
#                                                            ╠══════════════════════════╣
#                                                            ║                          ║
#                                                            ║       Made By Gugus      ║
#                                                            ║        For Ecoris        ║
#                                                            ║          With ♥️          ║
#                                                            ║                          ║
#                                                            ╚══════════════════════════╝

#╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬#
#╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬#
#╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬#


#                                                            ╔══════════════╗
#                                                            ║    IMPORT    ║
#                                                            ╚══════════════╝

import pyfiglet

from mega import Mega

from time import sleep

import os

import shutil

import emoji


#╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬#
#╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬#
#╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬#


#                                                            ╔═══════════════════╗
#                                                            ║    DEFINITIONS    ║
#                                                            ╚═══════════════════╝

class interface:

    def __init__(self) -> None:
        pass


    def wipe(n):
        try:
            os.system('cls')
        except:
            print("\n"*n)

    
    def isAdmin():
        interface.wipe(20)
        #interface.reload(EBP_List_Logiciel,EBP_List_Select)
        try:
            with open("C:/Windows/WindowsUpdate.log", 'w'):
                print("")
            os.system("del C:\\Windows\\WindowsUpdate.log")
            print(pyfiglet.Figlet(font='big').renderText(' ADMIN OK '))
            sleep(3)
            interface.wipe(20)
            os.system('cls' if os.name == 'nt' else 'clear')
            print('\n     - Vérification des mise à jours du système')
            resultmaj = os.popen('powershell -command "$session = New-Object -com "Microsoft.Update.Session"; "$searcher = $session.CreateUpdateSearcher()"; "$results = $searcher.search(\'IsInstalled=0\')"; " $results.updates.count"').read()
            if resultmaj.strip() == "0" :
                print('\n\n        Aucune mises à jours en attentes !')
                sleep(3)
            else:
                print('\n\n        Vous avez des mises à jours en attentes !\n          L\'installation risque de ne pas aboutir !')
                sleep(8)
            os.system('cls' if os.name == 'nt' else 'clear')
            interface.reload(EBP_List_Logiciel,EBP_List_Select)
        except PermissionError:
            print(pyfiglet.Figlet(font='big').renderText(' NOT ADMIN'))
            sleep(0.3)
            print('\n\n     Merci de relancer le script en Administrateur !\n')
            sleep(7)
            try:
                os.system(f"exit")
            except:
                exit()
            else:
                os._exit(0)


    def choix(choice,ebp,ebpselect):
        if choice.lower() == "A".lower() or choice.lower() == "ALL".lower():
            sleep(2)
            interface.wipe(40)
            interface.install(ebp)
        elif choice.lower() == "I".lower() or choice.lower() == "INSTALL".lower() or choice.lower() == "INSTALLATION".lower():
            if ebpselect:
                sleep(2)
                interface.wipe(40)
                interface.install(ebpselect)
            else:
                pass
        else:
            for elem in ebp:
                if choice.lower() == elem[0].lower():
                    ebpselect.append(elem)
                    ebp.remove(elem)
                    interface.wipe(10)
                    interface.reload(ebp,ebpselect)
            
            for elem in ebpselect:
                if choice.lower() == elem[0].lower():
                    ebp.append(elem)
                    ebpselect.remove(elem)    
                    interface.wipe(10)
                    interface.reload(ebp,ebpselect)


    def reload(ebp,ebpselect):
        print(pyfiglet.Figlet(font='big', width = 100).renderText('EBP Installer'))
        
        ebp.sort(key=lambda x: x[1])

        if ebp:
            print(f"{'   Logiciels disponibles :' if len(ebp)>1 else '   Logiciel disponible :'}")
            for elem in ebp:
                print(f"   [{elem[0]}]   {elem[1]}")
                sleep(0.05)
            print("\n   [A]   ALL\n\n")
            sleep(0.05)

        if ebpselect:
            print(f"{'   Logiciels sélectionnés :' if len(ebpselect)>1 else '   Logiciel sélectionné :'}")
            for elem in ebpselect:
                print(f"   [{elem[0]}]   {elem[1]}")
                sleep(0.05)
            print("\n   [I]   Lancer l'installation\n\n")
            sleep(0.05)


        choice = input("   Veuillez choisir parmi la liste ci-dessus.\n   >> ")

        interface.choix(choice,ebp,ebpselect)

        print("\n\n   Votre choix n'est pas valide !\n\n")

        sleep(1)

        interface.wipe(40)
        interface.reload(ebp,ebpselect)


    def install(list):
        mega = Mega()

        try:
            os.mkdir(os.environ['TEMP']+'\\EBP2022')
            print('\n     Dossier temporaire EBP2022 créé.\n')
        except PermissionError:
            print('\n     Impossible de créer un dossier temporaire.\n     Merci de relancer le script en Administrateur !\n')
            interface.nettoyage()
        except :
            print('\n     Dossier temporaire EBP2022 existant.\n')

        try:
            os.mkdir(os.environ['PROGRAMDATA']+'\\EBP')
            print('\n     Dossier PROGRAMDATA\EBP créé.\n')
        except PermissionError:
            print('\n     Impossible de créer un dossier temporaire.\n     Merci de relancer le script en Administrateur !\n')
            interface.nettoyage()
        except:
            print('\n     Dossier PROGRAMDATA\EBP existant.\n')

        sleep(3)
        interface.wipe(30)
        for elem in list:
            print(f"\n\n\n     • {elem[1]} | [{list.index(elem)+1}/{len(list)}]")
            if not os.path.isdir(elem[3]):
                print(f'\n\n\n        Téléchargement de {elem[1]} : en cours \n')
                try:
                    mega.download_url(elem[2],os.environ['TEMP']+'/EBP2022/')
                    print(f'\n        Téléchargement de {elem[1]} : OK \n')
                    print(f'\n\n               Installation de {elem[1]} : en cours \n')
                    if os.system("%temp% \\EBP2022\\"+elem[1]+".exe /s NETWORK=FALSE PERSONALIZED=TRUE WEBCHECKED=FALSE > nul") == 0: #
                        print(f"\n               Installation de {elem[1]} : OK\n")
                    else:
                        print(f"\n               Erreur ! L'installation de {elem[1]} a échoué !\n")
                        Failed_List.append(elem)
                        try:
                            os.system(f"echo Erreur installation {elem[1]} >> %userprofile%/Desktop/EBPInstaller_Rapport_Erreurs.txt")
                        except:
                            pass
                except WindowsError as a:
                    if os.path.isfile(os.environ['TEMP']+'/EBP2022/'+elem[1]+'.exe'):
                        print(f'\n        Téléchargement de {elem[1]} : OK \n')
                        print(f'\n\n               Installation de {elem[1]} : en cours \n')
                        if os.system("%temp%\\EBP2022\\"+elem[1]+".exe /s NETWORK=FALSE PERSONALIZED=TRUE WEBCHECKED=FALSE > nul") == 0: #
                            print(f"\n               Installation de {elem[1]} : OK\n")
                        else:
                            print(f"\n               Erreur ! L'installation de {elem[1]} a échoué !\n")
                            Failed_List.append(elem)
                            sleep(2)
                            try:
                                os.system(f"echo Erreur installation {elem[1]} >> %userprofile%/Desktop/EBPInstaller_Rapport_Erreurs.txt")
                            except:
                                pass
                    else:
                        print('\n        Fichier introuvable ! Merci de contacter informatique@ecoris.fr pour signaler cette erreur !\n')
                        Failed_List.append(elem)
                        sleep(2)
                        try:
                            os.system(f"echo Erreur Telechargement {elem[1]} >> %userprofile%/Desktop/EBPInstaller_Rapport_Erreurs.txt")
                        except:
                            pass
                except Exception as e:
                    print('\n        Fichier introuvable ! Merci de contacter informatique@ecoris.fr pour signaler cette erreur !\n')
                    Failed_List.append(elem)
                    sleep(2)
                    try:
                        os.system(f"echo Erreur Telechargement {elem[1]} >> %userprofile%/Desktop/EBPInstaller_Rapport_Erreurs.txt")
                    except:
                        pass
                
                sleep(1)
            else:
                print(f"\n\n        {elem[1]} est déjà installé [Dossier d'installation présent]\n")
                Failed_List.append(elem)
                sleep(2)
        sleep(2)
        interface.licenseXML(list,Failed_List)

    def licenseXML(list,error):

        for elem in error:
            try:
                list.remove(elem)
            except:
                pass

        if list:
            if os.path.isfile(os.environ['PROGRAMDATA']+'\\EBP\\license.xml'):
                print("\n\n     Un fichier de licence existe.\n")
                try:
                    with open(os.environ['PROGRAMDATA']+'\\EBP\\license.xml', 'r') as fr:
                        lines = fr.readlines()
                        with open(os.environ['PROGRAMDATA']+'\\EBP\\license-new.xml', 'w') as fw:
                            for line in lines:
                                if line.strip('\n') != '</ApplicationsLicenses>':
                                    fw.write(line)
                            for elem in list:
                                fw.write(elem[4][1:] if list.index(elem)==0 else elem[4])

                            fw.write('\n</ApplicationsLicenses>')
                        fw.close()
                    fr.close()
                    with open(os.environ['PROGRAMDATA']+'\\EBP\\license-new.xml', 'r+') as fd:
                        lines = fd.readlines()
                        fd.seek(0)
                        fd.writelines(line for line in lines if line.strip())
                        fd.truncate()
                    fd.close()

                    path = os.replace(os.environ['PROGRAMDATA']+'\\EBP\\license-new.xml', os.environ['PROGRAMDATA']+'\\EBP\\license.xml')
                    print("\n\n     Fichier de licence modifié !\n")
                except:
                    print("\n\n     Une erreur est survenue lors de la modification du fichier de licence !\n        Merci de contacter informatique@ecoris.fr pour signaler cette erreur !\n")
            else:
                print("\n\n     Aucun fichier de licence existant.\n")
                try:
                    with open(os.environ['PROGRAMDATA']+'\\EBP\\license.xml', 'w') as fw:
                        fw.write('<ApplicationsLicenses>\n')
                        for elem in list:
                                fw.write(elem[4][1:] if list.index(elem)==0 else elem[4])
                        fw.write('\n</ApplicationsLicenses>')
                    fw.close()

                    with open(os.environ['PROGRAMDATA']+'\\EBP\\license.xml', 'r+') as fd:
                        lines = fd.readlines()
                        fd.seek(0)
                        fd.writelines(line for line in lines if line.strip())
                        fd.truncate()
                    fd.close()
                    
                    print("\n\n     Fichier de licence créé !\n")
                except:
                    print("\n\n     Une erreur est survenue lors de la création du fichier de licence !\n        Merci de contacter informatique@ecoris.fr pour signaler cette erreur !\n")
                    print("\n\n     Cette version est le code source de EBPInstaller2022.\n     Celle-ci ne comporte pas de licence !\n")
        else:
            print("\n\n     Aucune nouvelle application n'a été installée.\n")
            sleep(2)
        interface.nettoyage()
    
    def nettoyage():
        sleep(3)
    
        if os.path.isdir(os.environ['TEMP']+'\\EBP2022'):
            try:
                shutil.rmtree(os.environ['TEMP']+'\\EBP2022')
                print('     Dossier temporaire EBP2022 supprimé.')
            except:
                print('     Impossible de supprimer le dossier temporaire EBP2022 !\n   Merci de vous rendre dans %temp% et de supprimer le dossier EBP2022')

        sleep(5)

        try:
            os.system(f"exit")
        except:
            exit()
        else:
            os._exit(0)

#╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬#
#╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬#
#╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬#


#                                                            ╔═══════════════════════╗
#                                                            ║    VARIABLES FIXES    ║
#                                                            ╚═══════════════════════╝


EBP_List_Logiciel =[
["Q","EBPOL_2022_Autonome_Paie_13_14_0_13423","https://mega.nz/file/AONFyC4L#R6WNqniUKo53vq0zbDUMA6cBE6tKah7z2-S20Pge4bQ","C:\\Program Files\\EBP\\Payroll13.14FRFR50"],
["S","EBPOL_2022_Classic_BusinessPlan_14_0_0_2005","https://mega.nz/file/Na0Q3QDR#7rO8M_acqY9-AwaP3cgxjh6r3LrBvliu8t-myvCYlyQ","C:\\Program Files\\EBP\\BusinessPlan14.0FRFR20"],
["D","EBPOL_2022_LigneOL_CRM_14_0_0_1201","https://mega.nz/file/0D8wxLzY#f1lgrzkx0lvfQuLL_WMXHzT87UmfYOoCo60hFD1LlRw","C:\\Program Files\\EBP\\CRM14.0FRFR40"],
["F","EBPOL_2022_LigneOL_Immos_14_0_0_3619","https://mega.nz/file/VfNDjDQT#Dv4pkwA2ffQ96sr1Wgw7DxupkNYgh29q3Qj7bJhXKBI","C:\\Program Files\\EBP\\CapitalAsset14.0FRFR40"],
["G","EBP_2022_Comptabilite_ELITE_21_0_0_9593","https://mega.nz/file/Ne1DkYqD#SLvfwS87Q-9hPxfPi9cTAuX4LXVM8Z6GYJQzNT68f7s","C:\\Program Files\\EBP\\Accounting21.0FRFR40"],
["H","EBP_2022_Etats_Financiers_PRO_21_3_1_3765","https://mega.nz/file/pLt0gKjK#83t7ckEzf_iVNGnFYbyE56ru-_-3l9jeSsKE4gRJo74","C:\\Program Files\\EBP\\FinState21.3FRFR30"],
["J","EBP_2022_Gestion_ELITE_21_1_0_6632","https://mega.nz/file/4DdgHBBK#R6jsDhpc7Ad5638_GFAmikD28SWuwK7R4THAjoncmXw","C:\\Program Files\\EBP\\Invoicing21.1FRFR40"]
]

EBP_List_Select = []

Failed_List=[]

#╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬#
#╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬#
#╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬#


#                                                            ╔════════════╗
#                                                            ║    CODE    ║
#                                                            ╚════════════╝


interface.isAdmin()



#╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬#
#╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬#
#╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬#
